### ISSUE TITLE
Output in application not displaying correctly on production server

### ISSUE THREAD

**Issue by wwwroth** [inspheric/nova-url-field#10]
Hello!

Using this package to display links to download files inside tables. I have it working fine on local, but when I deploy I'm getting some unexpected behavior on the app.

Local:
```html
<a href="https://-----" target="_blank" class="cursor-pointer dim no-underline text-primary flex items-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" role="presentation" class="fill-current mr-2 flex-no-shrink"><path d="M19-----"></path></svg> <span class="block truncate">
            Download
        </span></a>
```

Production server:
```html
<index-url-field resource-name="files" via-resource="contacts" via-resource-id="14440" field="[object Object]" class="text-left"></index-url-field>
```

Any ideas on what could be causing this?

**Comment by kitbs** [comment]
Hi @wwwroth. That's unusual. It looks like the component hasn't been properly rendered by Vue. Are there any JavaScript console errors or is there a 404 for the field.js in your browser's dev tools? Are you running `npm run prod` when you deploy, and are there any errors from that?
