### ISSUE TITLE
rel nofollow

### ISSUE THREAD

**Issue by andrewtweber** [inspheric/nova-url-field#12]
Would be great to have a `nofollow` option.

As a quick attempt, I tried extending the Url class

```php
use Inspheric\Fields\Url as BaseUrl;

class Url extends BaseUrl {
    public function nofollow() {
        return $this->withMeta(['rel' => 'nofollow']);
    }
}
```

But unfortunately that doesn't seem to work. Maybe the meta tags are restricted?

**Comment by kitbs** [comment]
Hi @andrewtweber

Nova's meta keys are not the same thing as HTML attributes. A meta key will only appear as an HTML attribute if the package developer has specifically implemented it that way.

I wonder what your use case for wanting nofollow is though. The Nova application is behind a login so the pages that these links are displayed on will not be accessible to search engines and robots anyway.

**Comment by andrewtweber** [comment]
Sorry, brain fart on the search engine stuff :) Thanks for the explanation on the meta keys, I just started with Nova yesterday so haven't been able to dive into the source much yet

**Comment by kitbs** [comment]
Hey, no worries. Hope you enjoy getting into Nova!
