### ISSUE TITLE
Styling option like relationship url

### ISSUE THREAD

**Issue by tpetry** [inspheric/nova-url-field#13]
It would be nice in some cases to have a styling option so the url looks like e.g. the BelongsTo url on detail pages. So this package could be used to link to specific resources within nova without having a defined relationship and looking like everything else in nova.

**Comment by kitbs** [comment]
Hi @tpetry. I just added a new `customHtml()` method ([docs](https://github.com/inspheric/nova-url-field#custom-html)) which will let you style the link however you like.
