### ISSUE TITLE
Should work with computed values

### ISSUE THREAD

**Issue by niladam** [inspheric/nova-url-field#2]
I think this should also work with computed values -- however, right now it doesn't.

**Comment by kitbs** [comment]
https://github.com/laravel/nova-issues/issues/345#issuecomment-417352725

**Comment by kitbs** [comment]
Hi @niladam 

You can do this:

```php
Url::make('Homepage', function() {
   return 'https://www.example.com';
}),
```

Or did you mean using a computed value as the label? I have just added a `labelUsing()` method which accepts a callback:

```php
Url::make('Homepage')->labelUsing(function() {
    return $this->title;
}),
```

Otherwise, can you be more specific?
