### ISSUE TITLE
Urls without http:// 

### ISSUE THREAD

**Issue by Milkhan** [inspheric/nova-url-field#3]
Is it possible to just put urls without http://? Currently it refuses.

**Comment by kitbs** [comment]
This is because the field is type="url". I will look at resolving it under #4 .

**Comment by kitbs** [comment]
Hi @Milkhan 

I have enabled the ability to change the HTML field type from `url` using `withMeta` (same as the built-in Nova text field), so you could do something like:

```php
Url::make(__('Website'), 'website')
    ->withMeta(['type' => 'text'])
    ->displayUsing(function($website) {
        return 'http://' . $website;
    })
    ->clickable(),
```

Although it would be up to you to validate the URL and figure out whether you do or don't need to add "http://" in the `displayUsing()` based on what the user has entered.
