### ISSUE TITLE
Nova 4: Row click interferes and opens the resource instead of the URL

### ISSUE THREAD

**Issue by tzsk** [inspheric/nova-url-field#38]
Nova Version: ^4.0
URL Field Version: ^2.0

I think they changed the index page row click behavior in Nova 4. Now if you click on any regular fields in the Row it opens the Resource Detail page. Which creates interference for this URL field. I think you need to wrap the field in a div and stop the click event bubbling up to the resource view level.

**Comment by jimbojsb** [comment]
Would be great to get this merged and tagged.

**Comment by kitbs** [comment]
Thanks very much for picking this up @tzsk !

**Comment by jimbojsb** [comment]
Hmm, I expected this would work, but it doesn't actually seem to for me. Using 2.0.2 of this package and nova 4.19.3

**Comment by kitbs** [comment]
@jimbojsb It worked for me when I tested it before release. Can you try clearing your browser cache to ensure the previous assets are not cached?

**Comment by jimbojsb** [comment]
@kitbs sigh. Yep that does it. Thanks.

**Comment by kitbs** [comment]
@jimbojsb Great to hear! Thanks for using the package
