### ISSUE TITLE
Allow disabling url type for input

### ISSUE THREAD

**Issue by Livijn** [inspheric/nova-url-field#4]
I am using this package for the display purpose only. When updating the model, it requires a URL. But as you can see in my code, I am using only a part of the URL.

    Url::make('Instagram', 'instagram_username')
                ->displayUsing(function ($instagram) {
                    return 'https://instagram.com/' . $instagram;
                })
                ->clickable()
                ->hideFromIndex(),

**Comment by kitbs** [comment]
For this use case, I would recommend using a pair of fields, one editable `Text` shown on forms and the other a `Url` for display only, shown on detail/index:

```php
Text::make(__('Instagram'), 'website')
    ->onlyOnForms(),

Url::make(__('Instagram'), 'instagram_username')
    ->labelUsing(function() {
        return '@'.$this->instagram_username;
    })
    ->displayUsing(function($instagram) {
        return 'https://instagram.com/' . $instagram;
    })
    ->onlyOnDetail()
    ->clickable(),
```
