### ISSUE TITLE
displayUsing support.

### ISSUE THREAD

**Issue by greggh** [inspheric/nova-url-field#5]
This field is great, huge help. I use it extensively. But it doesn't support displayUsing when a field gets shortened.

```
            Url::make(__('URL'), 'url')
                ->rules('required')
                ->sortable()
                ->displayUsing(function ($title) {
                    return str_limit($title, 25, '...');
                })->clickable()->clickableOnIndex()->onlyOnIndex()
            ,
```

Some URLs are actually longer, and so they end up looking like "https://www.somedomain.c..." because of displayUsing. They get turned into links, but when clicked, you end up going to "https://www.somedomain.c..." instead of the real URL.

**Comment by kitbs** [comment]
`displayUsing` is designed to modify the field's actual value before displaying it, the way someone described on #4.

I think what you're trying to do would work better with the [`label`](https://github.com/inspheric/nova-url-field#label) function. Can you see if this works?
```php
URL::make(...)->label(str_limit($this->url, 25, '...'))
```

**Comment by kitbs** [comment]
Great, glad to help

**Comment by kitbs** [comment]
@greggh FYI I am about to add a release with a new method `labelUsing()` which accepts a callback, which would be better suited to your use case, as it resolves properly on the resource:

```php
Url::make(...)->labelUsing(function() {
    return str_limit($this->url, 25, '...');
}),
```
