### ISSUE TITLE
URL label cannot be derived from model data

### ISSUE THREAD

**Issue by tylernathanreed** [inspheric/nova-url-field#7]
I have a scenario where I want both the link and the label to be based on the model data. However, it appears that I'm currently only able to make the link dynamic.

**Comment by kitbs** [comment]
Hi @tylernathanreed 

Could you try something like this?

```php
Url::make('Homepage', 'model_attribute_for_url')
    ->label($this->model_attribute_you_want_as_label),
```

**Comment by tylernathanreed** [comment]
@kitbs,

That would only work in limited scenarios. The field declarations is typically done with an empty resource, so the "$this" scope isn't called for each resource. This is why Nova uses a closure.

I would expect this sort of functionality to work:

```php
Url::make('Homepage', 'model_attribute_for_url')
    ->label(function() {
        return $this->model_attribute_you_want_as_label;
    }),
```

As that is how Nova expects computed properties to behave.

However, this package doesn't currently support passing in a closure for labels.

**Comment by kitbs** [comment]
@tylernathanreed 

I see what you mean. I've just pushed a commit to add the method `labelUsing` which accepts a callback.

```php
Url::make('Homepage')
    ->labelUsing(function($value, $resource) {
        return $this->title;
    }),
```

I've got a few more improvements to make tonight so I'll create a release soon.
